### ISSUE TITLE
CharlieYu的个人博客

### ISSUE THREAD

**Issue by CharlieYu4994** [CharlieYu4994/charlieyu4994.github.io#4]
https://charlieyu4994.github.io/friends/ 

 就只是博客而已

**Comment by CharlieYu4994** [comment]
若要添加友链，请在评论时说明 __网站链接__ 和 __头像链接__ 还有你想要显示的 __昵称__

**Comment by Nofated095** [comment]
希望添加友链（
|key|value|
|:-:|:-:|
|站点名称|Nofated's Blog|
|站点描述|I hope to be with you everyday.|
|站点链接|https://nofated.restent.win|
|头像链接|https://pic.rmb.bdstatic.com/bjh/020a46e8318d66b55d73afe31805d653.jpeg|

**Comment by CharlieYu4994** [comment]
> @Nofated095
> 希望添加友链（
> |key|value|
> |:-:|:-:|
> |站点名称|Nofated's Blog|
> |站点描述|I hope to be with you everyday.|
> |站点链接|https://nofated.restent.win|
> |头像链接|https://pic.rmb.bdstatic.com/bjh/020a46e8318d66b55d73afe31805d653.jpeg|

OK

**Comment by Qubik65536** [comment]
希望可以添加友链
``` yml
{
    "title": "Cubik的小站",
    "url": "https://cubik65536.top",
    "avatar": "https://cdn.jsdelivr.net/gh/Cubik65536/cubik-favicons@main/CubikLogo.png",
    "screenshot": "https://img.cubik65536.top/Cubik65536.github.io-Screenshot.png",
    "description": "RECOMMENDED BY DR.CREATIVE",
}
```
